apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: microservices
spec:
  type: LoadBalancer   #  AWS ELB will be provisioned
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 8080  # container port
